package org.bak.inflationmemorygame.values

object Constants {
    const val DEFAULT_FLIP_COUNT = 2

    const val PRELOAD_INTERVAL = 500L
    const val GAME_FLOW_INTERVAL_NORMAL = 300L

    const val MESSAGE_ADD_INTERVAL_IN_MILLIS_NORMAL = 500L
    const val MESSAGE_DURATION_MILLIS_NORMAL = 3_000L

    const val VISUAL_EFFECT_APPEAR_INITIAL_OFFSET_PX = -20f
    const val VISUAL_EFFECT_APPEAR_DURATION_MILLIS = 500
    const val VISUAL_EFFECT_FLIP_DURATION_MILLIS = 300
    const val VISUAL_EFFECT_RIPPLE_EACH_DURATION_MILLIS = 1_000
    const val VISUAL_EFFECT_RIPPLE_TOTAL_COUNT = 3

    const val CARDS_IN_EACH_ROW_COMPACT = 5
    const val CARDS_IN_EACH_ROW_WIDE = 10
}